---
kind: pipeline
type: docker
name: tlp

steps:
- name: test
  image: golang:1.13
  commands:
  - export GO111MODULE=on
  - go get -u github.com/CNSC2Events/tlp
  - go test -race -coverprofile=coverage.txt -covermode=atomic github.com/CNSC2Events/tlp
- name: codecov
  image: plugins/codecov
  settings:
    token:
      from_secret: CODECOV_TOKEN
    files:
    - coverage.txt
- name: build
  image: golang:1.13
  commands:
  - export GO111MODULE=on
  - go get -u github.com/CNSC2Events/tlp
  - go install github.com/CNSC2Events/tlp

